[project]
name = "generate_kanji_maps"
version = "0.1.0"
description = "a utility to generate kanji maps for use with the iced musical typing app"
readme="README.md"
requires-python = ">=3.12"
dependencies = [
  "pykakasi>=2.3.0",
  "requests>=2.32.5",
]
